version: 2
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/aws-get-web-identity-token
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
checksum:
  name_template: "checksums.txt"
homebrew_casks:
  - repository:
      owner: winebarrel
      name: homebrew-aws-get-web-identity-token
    homepage: https://github.com/winebarrel/aws-get-web-identity-token
    description: Get a web identity token (JWT) from AWS STS GetWebIdentityToken.
    license: MIT
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aws-get-web-identity-token"]
          end
nfpms:
  - file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
    homepage: https://github.com/winebarrel/aws-get-web-identity-token
    description: Get a web identity token (JWT) from AWS STS GetWebIdentityToken.
    license: MIT
    maintainer: "Genki Sugawara <sugawara@winebarrel.jp>"
    formats:
      - apk
      - deb
      - rpm
